config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: "search#index"
  resources :categories
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  devise_for :users

  root to: 'products#index'

  resources :products do
    member do
      delete "remove_image/:image_id", to: "products#remove_image", as: :remove_image
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :product, through: :orderables

  def total
    orderables.to_a.sum {|orderable| orderable.total}
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/orderable.rb
class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  validates :description, presence: true
  validates :category_id, presence: true
  validates :price, presence: true
  has_many_attached :images
  has_many :orderables
  has_many :carts, through: :orderables
  
  def self.ransackable_attributes(auth_object = nil)
    %w[category category_id created_at description id id_value name price updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[category images_attachments images_blobs]
  end
  
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :recoverable
  enum role: %i[user moderator admin]
  after_initialize :set_default_role, if: :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_query
  include Pundit

  def set_query
    @query = Product.ransack(params[:q])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_cart

  def show
    @cart = Cart.find_or_create_by(id: session[:cart_id])
    session[:cart_id] ||= @cart.id
  end
  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)

    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy if current_orderable
    else
      Orderable.create(product: @product, quantity: quantity, cart: @cart)
    end      
  end

  def remove
    Orderable.find_by(id: params[:id]).destroy
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])
    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] ||= @cart.id
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    authorize Category
  end

  # GET /categories/1 or /categories/1.json
  def show
    authorize @category
  end

  # GET /categories/new
  def new
    @category = Category.new
    authorize @category
  end

  # GET /categories/1/edit
  def edit
    authorize @category
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    authorize @category

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    authorize @category

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    authorize @category
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_categories
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render :new
    end
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
    authorize @product
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path, notice: 'Продукт видалено'
    authorize @product
  end

  def remove_image
    @image = ActiveStorage::Attachment.find(params[:image_id])
    @product = @image.record
    @image.purge_later
    redirect_back(fallback_location: request.referer)
    authorize @product
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    authorize @product
  end

  def edit
    @product = Product.find(params[:id])
    authorize @product
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :category_id, :price, images: [])
  end

  def set_categories
    @categories = Category.all.order(:name)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = Product.ransack(params[:q])
    @products = @query.result(distinct: true)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def total_price
    total_price = 0
    @cart.orderables.each do |orderable|
      total_price += orderable.total
    end
    total_price
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/cart/orderable.html.erb
<% @cart.orderables.each do |orderable| %>
  <% product = orderable.product %>
  <p><b><%= product.name %></b></p>
  <% if product.images.attached? %>
    <% product.images.each do |image| %>
      <%= image_tag(image, style: 'width:300px; height:300px;') %>
    <% end %>
  <% end %>
  <p><b>Description: </b><%= product.description %></p>
  <p><b>Price: </b><%= product.price %></p>
  <%= form_with(url: cart_add_path) do |f| %>
    <%= f.hidden_field :id, value: product.id %>
    <%= f.number_field :quantity, value: orderable.quantity, min: 1 %>
    <%= f.submit "Add to Cart" %>
  <% end %>

  <%= form_with(url: cart_remove_path) do |f| %>
    <%= f.hidden_field :id, value: orderable.id %>
    <%= f.submit "X" %>
  <% end %>   
  <p>Total: <%= orderable.total %></p>
<% end %>

app/views/cart/show.html.erb
<%= turbo_frame_tag "cart" do %>
  <h1><b>Cart</b></h1>

  <% if @cart.orderables.count > 0 %>
    <% @cart.orderables.each do |orderable| %>
      <% product = orderable.product %>
      <p><b><%= product.name %></b></p>
      
      <% if product.images.attached? %>
        <%= image_tag(product.images.first, style: 'width:300px; height:300px;') %>
      <% end %>
      
      <p>Quantity: <%= orderable.quantity %></p>
      <p><b>Price: </b><%= product.price %></p>

      <%= form_with(url: cart_remove_path) do |f| %>
        <%= f.hidden_field :id, value: orderable.id %>
        <%= f.submit "Remove from cart" %>
      <% end %>
    <% end %>
    <p> Total price: <%= total_price %></p>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>

<% end %>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= category.name %>
  </p>

  <div>
    <strong class="block font-medium mb-1">Products:</strong>
    <% products = Product.where(category_id: category.id) %>
    <% if products.any? %>
      <ul>
        <% products.each do |product| %>
          <li>
            <%= link_to "#{product.name} - #{product.description}", product_path(product) %>
          </li>
          <!-- Add more details based on your product model -->
        <% end %>
      </ul>
    <% else %>
      <p>No products in this category.</p>
    <% end %>
  </div>

  <% if action_name != "show" %>
  
    <%= link_to "Show this category", category, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if current_user.admin? %>
      <%= link_to "Edit this category", edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <% if current_user.admin? %>
      <%= link_to "New category", new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="categories" class="min-w-full">
    <%= render @categories %>
  </div>

  <div>
    <p><b><%= link_to "Всі продукти", products_path, style: "font-size: 22px;" %></b></p>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
    <%= render @category %>

    <% if current_user %>
      <% if current_user.admin? %>
      <%= link_to "Edit this category", edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <% end %>
      <div class="inline-block ml-2">
      </div>
    <% end %>

    <% if current_user %>
      <% if current_user.admin? %>
        <%= button_to "Destroy this category", category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      <% end %>
    <% end %>
    <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<div>
  <% if !user_signed_in?%>
    <%= link_to "Sign in", new_user_session_path%>
    <%= link_to "Sign up", new_user_registration_path%>
  <%else%>
    <p>Hello <%=current_user.email%></p>
    <p>You are a [<%= current_user.role %>]</p>
    <%= button_to "Log out", destroy_user_session_path, method: :delete%>
  <%end%>
</div>

app/views/products/create.html.erb
<h2>Продукт додано</h2>

app/views/products/destroy.html.erb
Продукт видалено!

app/views/products/edit.html.erb
<h2>Зміна відомостей про продукт <%= @product.name %></h2>

<%= form_with model: @product do |form| %>
    <p><%= form.label :name, 'Назва продукта' %></p>
    <p><%= form.text_field :name%></p>
    <p><%= form.label :description %></p>
    <p><%= form.text_area :description, rows: 1  %></p>
    <p>Категорія</p>
    <p><%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})%>
    <p><%= form.label :price, 'Ціна' %></p>
    <p><%= form.text_field :price%></p>
    <p><%= form.label :images, "Select photo" %></p>
    <% if @product.images.attached? %>
      <% @product.images.each do |image| %>
        <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
        <%= image_tag(image, style: 'width:300px; height:300px;') %>
      <% end %>
    <% end %>
    <%= form.file_field :images, multiple: true %>
    <p><%= form.submit 'Зберегти зміни' %></p>
  <% end %>
  

app/views/products/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
    <h2 class="sr-only">Products</h2>

    <div class="grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
      <% @products.each do |product| %>
        <a href="<%=product_path(product.id)%>" class="group">
          <div class="aspect-h-1 aspect-w-1 w-full overflow-hidden rounded-lg bg-gray-200 xl:aspect-h-8 xl:aspect-w-7">
            <% if product.images.attached? %>
              <%= image_tag(product.images.first, class: 'h-full w-full object-cover object-center group-hover:opacity-75') %>
            <% end %>
          </div>
          <h3 class="mt-4 text-sm text-gray-700"><%= product.name%></h3>
          <p class="mt-1 text-lg font-medium text-gray-900"><%= product.price %></p>
        </a>
      <% end %>
      <!-- More products... -->
    </div>
  </div>
</div>

<% if current_user %>
  <% if current_user.admin? %>
    <p><%= link_to "Добавити продукт", new_product_path %></p> 
  <%end%>
  <p><%= link_to "Переглянути категорії", categories_path %></p>
<%end%>

app/views/products/new.html.erb
<h2>Додати продукт</h2>

<%= form_with model: @product do |form| %>
  <p><%= form.label :name, 'Назва продукта' %></p>
  <p><%= form.text_field :name%></p>
  <p><%= form.label :description, 'Опис' %></p>
  <p><%= form.text_area :description, rows: 1  %></p>
  <p>Категорія</p>
  <p><%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})%>
  <p><%= form.label :price, 'Ціна' %></p>
  <p><%= form.text_field :price%></p>
  <p><%= form.label :images, 'Оберіть фото' %></p>
  <% if @product.images.attached? %>
    <% @product.images.each do |image| %>
      <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
    <% end %>
  <% end %>
  <%= form.file_field :images, multiple: true %>
  <p><%= form.submit 'Добавити продукт' %></p>
  
<% end %>

app/views/products/show.html.erb
<h1>Продукт</h1>
<p><b><%= @product.name %></b></p>

<% if @product.images.attached? %>
  <% @product.images.each do |image| %>
    <%= image_tag(image, style: 'width:300px; height:300px;') %>
    <% if current_user %>
      <% if current_user.admin? %>
        <%= button_to "Remove image", remove_image_product_path(image, image_id: image.id), method: :delete, remote: true %>
      <%end%>
    <%end%>
  <% end %>
<%end%>

<p><b>description: </b><%= @product.description %></p>
<p><b>Category: </b><%= link_to @product.category&.name, @product.category %></p>
<p><b>Price: </b><%= @product.price %></p>
<% if current_user %>
  <% if current_user.admin? %>
  <p><%= link_to "Відредагувати", edit_product_path(@product) %></p>
  <%= button_to 'Видалити продукт', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' } %>
  <%end%>
<%end%>
<%= form_with(url: cart_add_path) do |f| %>
  <%= f.hidden_field :id, value: @product.id %>
  <%= f.number_field :quantity, value: 0, min: 1 %>
  <%= f.submit "Add to Cart" %>
<% end %>
<p><%= link_to "Всі продукти", products_path %></p>

app/views/products/update.html.erb
Продукт зміненно!

app/views/search/_form.html.erb
<%= search_form_for(@query, url: search_path) do |f| %>
  <%= f.search_field :name_or_description_or_price_eq, placeholder: "Search..." %>
  <%= f.submit "Search!" %>
<% end %>

app/views/search/index.html.erb
<div>
  <h1 class="text-center"><%= pluralize(@products.count, "Result") %></h1>
</div>

<div class="container mx-auto my-4">
  <table class="w-full bg-white border border-gray-300">
    <thead>
      <tr class="bg-gray-100">
        <th class="py-2 px-4 border-b"><%= sort_link(@query, :name, "Name") %></th>
        <th class="py-2 px-4 border-b"><%= sort_link(@query, :description, "Description") %></th>
        <th class="py-2 px-4 border-b"><%= sort_link(@query, :price, "Price") %></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr class="hover:bg-gray-50">
          <td class="py-2 px-4 border-b"><%= link_to product.name, product, class: "text-blue-500" %></td>
          <td class="py-2 px-4 border-b"><%= product.description.truncate_words(25) %></td>
          <td class="py-2 px-4 border-b"><%= product.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>